import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="min-h-screen bg-black flex flex-col">
          {/* Add flag-colored line globally in layout */}
          <div className="h-1 bg-gradient-to-r from-[#ffffff] via-[#009639] to-[#d71a3f] mb-4"></div>

          {/* Render children (this will be the page content) */}
          <main className="flex-grow p-8 bg-black">{children}</main>
        </div>
      </body>
    </html>
  );
}
